//! Clock-injected session authority (plan sections 6.3, 7, and 15.1).
//!
//! Observation, view readiness, and control are independent. All time-bearing
//! decisions are serialized through this owner, including submission checks:
//! callers must sample the host clock immediately before OS submission, not
//! reuse a packet's arrival timestamp. Foreign calls and held-key cleanup are
//! outside this module and must not hold the authority owner's lock.
//!
//! Deadlines are exclusive. Renewals use the deadline fixed when a challenge
//! was issued, not a fresh lifetime starting when a buffered reply arrives.
//! Clock regression fences the session terminally. Opaque IDs/nonces must be
//! freshly generated by the qualified host adapter; this module is not RNG,
//! peer authentication, global controller-slot arbitration, or OS injection.

use crate::ids::{InputLeaseId, InputTicketId, RemoteSessionId};
use crate::time::{HostDuration, HostInstant};

/// Bounded host authorization and input-ticket lifetime policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AuthorityPolicy {
    /// Provisional lifetime of observation/control authorization.
    pub authorization_lifetime: HostDuration,
    /// Ticket lifetime, clamped to observation and control authorization.
    pub ticket_lifetime: HostDuration,
}

impl AuthorityPolicy {
    /// The plan's provisional three-second authorization and one-second ticket.
    #[must_use]
    pub fn plan_defaults() -> Self {
        Self {
            authorization_lifetime: HostDuration::from_millis_checked(3_000)
                .expect("3s fits u64 micros"),
            ticket_lifetime: HostDuration::from_millis_checked(1_000).expect("1s fits u64 micros"),
        }
    }
}

/// Coarse lifecycle, independent of observation, readiness, and control.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Phase {
    /// Identified transport; only bounded negotiation admitted.
    Identified,
    /// Capabilities checked; observation not yet authorized.
    CapabilitiesChecked,
    /// Local approval pending; no observation admitted.
    WaitingApproval,
    /// Observation authorized; no usable view yet.
    ViewOpening,
    /// Observation authorized and view has opened.
    Viewing,
    /// Terminal refusal.
    Refused,
    /// Terminal closure/fence.
    Closed,
}

/// Typed, content-free refusal reasons.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum AuthorityError {
    /// Operation illegal in the current lifecycle phase.
    InvalidState {
        /// The current phase.
        phase: Phase,
    },
    /// Observation is absent or its deadline has been reached.
    ObservationExpired,
    /// No control lease is held.
    NoLease,
    /// Referenced lease is not the current lease.
    StaleLease,
    /// Control authorization has reached its exclusive deadline.
    LeaseExpired,
    /// A current trustworthy view is required.
    ViewUnready,
    /// A live control lease already occupies this session's slot.
    ControllerBusy,
    /// An expired lease must be revoked/cleaned up before replacement.
    ControllerCleanupRequired,
    /// Ticket is unknown, replaced, or belongs to another lease.
    TicketInvalid,
    /// Ticket has reached its exclusive deadline.
    TicketExpired,
    /// No matching challenge is outstanding.
    ChallengeMismatch,
    /// An unexpired challenge is still awaiting its response.
    ChallengePending,
    /// Challenge has reached its exclusive deadline.
    ChallengeExpired,
    /// A host-clock regression fenced this session terminally.
    ClockRegression,
    /// Deadline arithmetic overflowed or cannot produce a future deadline.
    DeadlineOverflow,
}

/// Whether presented source state is trustworthy enough for input.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewReadiness {
    /// No usable view yet.
    Unready,
    /// A current, presented, trustworthy view.
    Ready,
    /// Presentation is stale/unknown; old submission tickets are invalid.
    Stale,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Challenge {
    nonce: u128,
    deadline: HostInstant,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Lease {
    id: InputLeaseId,
    authorized_until: HostInstant,
    ticket: Option<Ticket>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Ticket {
    id: InputTicketId,
    expires_at: HostInstant,
}

/// Serialized policy owner for one remote session. The containing OS-share
/// authority owner must arbitrate the single controller across all viewers.
/// Cloning is for deterministic state inspection, not independent controllers.
#[derive(Debug, Clone)]
pub struct SessionAuthority {
    session: RemoteSessionId,
    policy: AuthorityPolicy,
    phase: Phase,
    observation_until: Option<HostInstant>,
    readiness: ViewReadiness,
    lease: Option<Lease>,
    observation_challenge: Option<Challenge>,
    control_challenge: Option<Challenge>,
    last_checked: Option<HostInstant>,
    clock_faulted: bool,
}

impl SessionAuthority {
    /// Opens a freshly identified session with no authority.
    #[must_use]
    pub fn new(session: RemoteSessionId, policy: AuthorityPolicy) -> Self {
        Self {
            session,
            policy,
            phase: Phase::Identified,
            observation_until: None,
            readiness: ViewReadiness::Unready,
            lease: None,
            observation_challenge: None,
            control_challenge: None,
            last_checked: None,
            clock_faulted: false,
        }
    }

    /// The remote session identity.
    #[must_use]
    pub fn session(&self) -> RemoteSessionId {
        self.session
    }

    /// The coarse lifecycle phase.
    #[must_use]
    pub fn phase(&self) -> Phase {
        self.phase
    }

    /// The current presentation readiness.
    #[must_use]
    pub fn readiness(&self) -> ViewReadiness {
        self.readiness
    }

    /// Advances bounded negotiation, without granting observation.
    pub fn mark_capabilities_checked(&mut self) -> Result<(), AuthorityError> {
        if self.phase != Phase::Identified {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        self.phase = Phase::CapabilitiesChecked;
        Ok(())
    }

    /// Enters approval pending. Only the trusted local approval owner may
    /// subsequently call `authorize_observation`; this is not a peer RPC.
    pub fn require_approval(&mut self) -> Result<(), AuthorityError> {
        if self.phase != Phase::CapabilitiesChecked {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        self.phase = Phase::WaitingApproval;
        Ok(())
    }

    /// Grants observation after admission and any required local approval.
    /// This starts a new grant with no retained challenge, lease, or readiness.
    pub fn authorize_observation(&mut self, now: HostInstant) -> Result<(), AuthorityError> {
        self.check_time(now)?;
        if !matches!(self.phase, Phase::CapabilitiesChecked | Phase::WaitingApproval) {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        let until = self.deadline_from(now)?;
        self.clear_authority();
        self.observation_until = Some(until);
        self.phase = Phase::ViewOpening;
        Ok(())
    }

    /// Checks observation immediately before releasing protected data.
    /// Successful negotiation or a control heartbeat is not a substitute.
    pub fn authorize_observation_delivery(
        &mut self,
        now: HostInstant,
    ) -> Result<(), AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)
    }

    /// Records a current, trustworthy presented view; never grants a lease.
    pub fn mark_view_ready(&mut self, now: HostInstant) -> Result<(), AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        self.phase = Phase::Viewing;
        self.readiness = ViewReadiness::Ready;
        Ok(())
    }

    /// Suspends input and invalidates old tickets. Recovery requires a new
    /// ticket even if the lease identity and observation remain live.
    pub fn mark_view_stale(&mut self) {
        if self.readiness == ViewReadiness::Ready {
            self.readiness = ViewReadiness::Stale;
        }
        if let Some(lease) = self.lease.as_mut() {
            lease.ticket = None;
        }
    }

    /// Issues one bounded observation challenge. A cadence tick cannot
    /// overwrite an unanswered live challenge and starve a high-RTT peer.
    pub fn issue_observation_challenge(
        &mut self,
        nonce: u128,
        now: HostInstant,
    ) -> Result<HostInstant, AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        Self::check_challenge_slot(self.observation_challenge, now)?;
        let deadline = self.deadline_from(now)?;
        self.observation_challenge = Some(Challenge { nonce, deadline });
        Ok(deadline)
    }

    /// Renews only still-live observation using the issue-time deadline.
    /// A reply cannot gain an additional lifetime just by arriving late.
    pub fn respond_observation_challenge(
        &mut self,
        nonce: u128,
        now: HostInstant,
    ) -> Result<HostInstant, AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        let challenge = Self::consume_challenge(&mut self.observation_challenge, nonce, now)?;
        self.observation_until = Some(challenge.deadline);
        Ok(challenge.deadline)
    }

    /// Grants this session's lease after the containing share-session owner
    /// reserves the global slot and completes previous-controller cleanup.
    /// Even an expired lease must be explicitly revoked before replacement.
    pub fn grant_lease(
        &mut self,
        lease_id: InputLeaseId,
        now: HostInstant,
    ) -> Result<(), AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        if self.phase != Phase::Viewing {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        if self.readiness != ViewReadiness::Ready {
            return Err(AuthorityError::ViewUnready);
        }
        if let Some(existing) = self.lease {
            return Err(if now < existing.authorized_until {
                AuthorityError::ControllerBusy
            } else {
                AuthorityError::ControllerCleanupRequired
            });
        }
        self.lease = Some(Lease {
            id: lease_id,
            authorized_until: self.deadline_from(now)?,
            ticket: None,
        });
        self.control_challenge = None;
        Ok(())
    }

    /// Issues one control challenge for the current, still-live lease.
    pub fn issue_control_challenge(
        &mut self,
        nonce: u128,
        now: HostInstant,
    ) -> Result<HostInstant, AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        let lease = self.lease.ok_or(AuthorityError::NoLease)?;
        if now >= lease.authorized_until {
            return Err(AuthorityError::LeaseExpired);
        }
        Self::check_challenge_slot(self.control_challenge, now)?;
        let deadline = self.deadline_from(now)?;
        self.control_challenge = Some(Challenge { nonce, deadline });
        Ok(deadline)
    }

    /// Renews the current lease to the matching challenge's fixed deadline.
    /// Observation remains an independent check at every submission.
    pub fn respond_control_challenge(
        &mut self,
        lease_id: InputLeaseId,
        nonce: u128,
        now: HostInstant,
    ) -> Result<HostInstant, AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        let lease = self.lease.as_mut().ok_or(AuthorityError::NoLease)?;
        if lease.id != lease_id {
            return Err(AuthorityError::StaleLease);
        }
        if now >= lease.authorized_until {
            self.control_challenge = None;
            return Err(AuthorityError::LeaseExpired);
        }
        let challenge = Self::consume_challenge(&mut self.control_challenge, nonce, now)?;
        lease.authorized_until = challenge.deadline;
        Ok(challenge.deadline)
    }

    /// Issues a new ticket, bounded by both observation and lease deadlines.
    /// Replacing a ticket invalidates its predecessor; callers use fresh IDs.
    pub fn issue_input_ticket(
        &mut self,
        lease_id: InputLeaseId,
        ticket_id: InputTicketId,
        now: HostInstant,
    ) -> Result<HostInstant, AuthorityError> {
        self.check_time(now)?;
        self.check_observation_live(now)?;
        if self.readiness != ViewReadiness::Ready {
            return Err(AuthorityError::ViewUnready);
        }
        let lease = self.lease.as_mut().ok_or(AuthorityError::NoLease)?;
        if lease.id != lease_id {
            return Err(AuthorityError::StaleLease);
        }
        if now >= lease.authorized_until {
            return Err(AuthorityError::LeaseExpired);
        }
        if lease.ticket.is_some_and(|ticket| ticket.id == ticket_id) {
            return Err(AuthorityError::TicketInvalid);
        }
        let uncapped = now
            .checked_add(self.policy.ticket_lifetime)
            .filter(|deadline| *deadline > now)
            .ok_or(AuthorityError::DeadlineOverflow)?;
        let expires_at = uncapped
            .min(lease.authorized_until)
            .min(self.observation_until.ok_or(AuthorityError::ObservationExpired)?);
        lease.ticket = Some(Ticket {
            id: ticket_id,
            expires_at,
        });
        Ok(expires_at)
    }

    /// Final policy check immediately before OS submission. Mutation records
    /// the monotonic clock high-water mark; this method never renews authority.
    /// Geometry, mapping, action sequences, and external cleanup are checked
    /// by their owning input adapter in addition to this session decision.
    pub fn authorize_submission(
        &mut self,
        lease_id: InputLeaseId,
        ticket_id: InputTicketId,
        now: HostInstant,
    ) -> Result<(), AuthorityError> {
        self.check_time(now)?;
        if self.phase != Phase::Viewing {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        self.check_observation_live(now)?;
        if self.readiness != ViewReadiness::Ready {
            return Err(AuthorityError::ViewUnready);
        }
        let lease = self.lease.ok_or(AuthorityError::NoLease)?;
        if lease.id != lease_id {
            return Err(AuthorityError::StaleLease);
        }
        if now >= lease.authorized_until {
            return Err(AuthorityError::LeaseExpired);
        }
        let ticket = lease.ticket.ok_or(AuthorityError::TicketInvalid)?;
        if ticket.id != ticket_id {
            return Err(AuthorityError::TicketInvalid);
        }
        if now >= ticket.expires_at {
            return Err(AuthorityError::TicketExpired);
        }
        Ok(())
    }

    /// Fences control synchronously. The input owner then releases held keys
    /// and buttons; this does not claim that OS cleanup has completed.
    pub fn revoke_lease(&mut self) {
        self.lease = None;
        self.control_challenge = None;
    }

    /// Checks live control against a current host-clock sample. This is not
    /// final submission authorization and does not validate an input ticket.
    #[must_use]
    pub fn has_live_control(&mut self, now: HostInstant) -> bool {
        self.check_time(now).is_ok()
            && self.check_observation_live(now).is_ok()
            && self.phase == Phase::Viewing
            && self.readiness == ViewReadiness::Ready
            && self.lease.is_some_and(|lease| now < lease.authorized_until)
    }

    /// Applies elapsed-deadline cleanup after a scheduling stall. An actual
    /// suspend/wake event MUST additionally call `invalidate_for_suspend`,
    /// because some OS clocks do not include suspended time.
    #[must_use]
    pub fn apply_resume_boundary(&mut self, now: HostInstant) -> bool {
        if self.check_time(now).is_err() {
            return false;
        }
        if self.observation_until.is_some_and(|until| now >= until) {
            self.drop_observation();
        }
        if self
            .observation_challenge
            .is_some_and(|challenge| now >= challenge.deadline)
        {
            self.observation_challenge = None;
        }
        if self
            .control_challenge
            .is_some_and(|challenge| now >= challenge.deadline)
        {
            self.control_challenge = None;
        }
        if self.lease.is_some_and(|lease| now >= lease.authorized_until) {
            self.revoke_lease();
        }
        if let Some(lease) = self.lease.as_mut()
            && lease.ticket.is_some_and(|ticket| now >= ticket.expires_at)
        {
            lease.ticket = None;
        }
        self.has_live_control(now)
    }

    /// Revokes observation and control even when the clock has not advanced.
    /// The local owner must reapply its approval policy before a new grant.
    pub fn invalidate_for_suspend(&mut self) {
        self.drop_observation();
    }

    /// Fences all access terminally before external cleanup begins.
    pub fn close(&mut self) {
        self.clear_authority();
        self.phase = Phase::Closed;
    }

    /// Refuses terminally, clearing observations, leases, tickets, and both
    /// challenge slots. No helper may report live authority after refusal.
    pub fn refuse(&mut self) {
        self.clear_authority();
        self.phase = Phase::Refused;
    }

    fn clear_authority(&mut self) {
        self.observation_until = None;
        self.readiness = ViewReadiness::Unready;
        self.lease = None;
        self.observation_challenge = None;
        self.control_challenge = None;
    }

    fn drop_observation(&mut self) {
        self.clear_authority();
        if matches!(self.phase, Phase::ViewOpening | Phase::Viewing) {
            self.phase = Phase::CapabilitiesChecked;
        }
    }

    fn check_time(&mut self, now: HostInstant) -> Result<(), AuthorityError> {
        if self.clock_faulted || self.last_checked.is_some_and(|previous| now < previous) {
            self.clock_faulted = true;
            self.close();
            return Err(AuthorityError::ClockRegression);
        }
        self.last_checked = Some(now);
        Ok(())
    }

    fn check_observation_live(&self, now: HostInstant) -> Result<(), AuthorityError> {
        if !matches!(self.phase, Phase::ViewOpening | Phase::Viewing) {
            return Err(AuthorityError::InvalidState { phase: self.phase });
        }
        match self.observation_until {
            Some(until) if now < until => Ok(()),
            _ => Err(AuthorityError::ObservationExpired),
        }
    }

    fn deadline_from(&self, now: HostInstant) -> Result<HostInstant, AuthorityError> {
        now.checked_add(self.policy.authorization_lifetime)
            .filter(|deadline| *deadline > now)
            .ok_or(AuthorityError::DeadlineOverflow)
    }

    fn check_challenge_slot(
        challenge: Option<Challenge>,
        now: HostInstant,
    ) -> Result<(), AuthorityError> {
        if challenge.is_some_and(|pending| now < pending.deadline) {
            Err(AuthorityError::ChallengePending)
        } else {
            Ok(())
        }
    }

    fn consume_challenge(
        slot: &mut Option<Challenge>,
        nonce: u128,
        now: HostInstant,
    ) -> Result<Challenge, AuthorityError> {
        let challenge = slot.ok_or(AuthorityError::ChallengeMismatch)?;
        if challenge.nonce != nonce {
            return Err(AuthorityError::ChallengeMismatch);
        }
        *slot = None;
        if now >= challenge.deadline {
            return Err(AuthorityError::ChallengeExpired);
        }
        Ok(challenge)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ids() -> (RemoteSessionId, InputLeaseId, InputTicketId) {
        (
            RemoteSessionId::from_raw(1),
            InputLeaseId::from_raw(2),
            InputTicketId::from_raw(3),
        )
    }

    fn at(micros: u64) -> HostInstant {
        HostInstant::from_micros(micros)
    }

    fn viewing_with_control(t0: HostInstant) -> (SessionAuthority, InputLeaseId, InputTicketId) {
        let (session, lease, ticket) = ids();
        let mut authority = SessionAuthority::new(session, AuthorityPolicy::plan_defaults());
        authority.mark_capabilities_checked().unwrap();
        authority.authorize_observation(t0).unwrap();
        authority.mark_view_ready(t0).unwrap();
        authority.grant_lease(lease, t0).unwrap();
        authority.issue_input_ticket(lease, ticket, t0).unwrap();
        (authority, lease, ticket)
    }

    #[test]
    fn first_frame_does_not_grant_control() {
        let (session, lease, _) = ids();
        let mut a = SessionAuthority::new(session, AuthorityPolicy::plan_defaults());
        a.mark_capabilities_checked().unwrap();
        a.authorize_observation(at(0)).unwrap();
        assert_eq!(
            a.grant_lease(lease, at(0)),
            Err(AuthorityError::InvalidState { phase: Phase::ViewOpening })
        );
        a.mark_view_ready(at(0)).unwrap();
        assert!(!a.has_live_control(at(0)));
        a.mark_view_stale();
        assert_eq!(a.grant_lease(lease, at(0)), Err(AuthorityError::ViewUnready));
    }

    #[test]
    fn submission_check_holds_lease_ticket_expiry_and_readiness() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        assert_eq!(a.authorize_submission(lease, ticket, at(500_000)), Ok(()));
        assert_eq!(
            a.authorize_submission(lease, InputTicketId::from_raw(99), at(500_000)),
            Err(AuthorityError::TicketInvalid)
        );
        assert_eq!(
            a.authorize_submission(InputLeaseId::from_raw(99), ticket, at(500_000)),
            Err(AuthorityError::StaleLease)
        );
        assert_eq!(
            a.authorize_submission(lease, ticket, at(1_000_000)),
            Err(AuthorityError::TicketExpired)
        );
    }

    #[test]
    fn stale_view_suspends_submission_without_dropping_the_lease() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        a.mark_view_stale();
        assert_eq!(
            a.authorize_submission(lease, ticket, at(100_000)),
            Err(AuthorityError::ViewUnready)
        );
        a.mark_view_ready(at(150_000)).unwrap();
        assert!(a.has_live_control(at(150_000)));
        assert_eq!(
            a.authorize_submission(lease, ticket, at(200_000)),
            Err(AuthorityError::TicketInvalid)
        );
        let fresh = InputTicketId::from_raw(4);
        a.issue_input_ticket(lease, fresh, at(200_000)).unwrap();
        assert_eq!(a.authorize_submission(lease, fresh, at(200_000)), Ok(()));
    }

    #[test]
    fn delayed_challenge_response_after_expiry_does_not_resurrect() {
        let (mut a, _, _) = viewing_with_control(at(0));
        a.issue_observation_challenge(0xabc, at(1_000_000)).unwrap();
        assert_eq!(
            a.respond_observation_challenge(0xabc, at(3_000_000)),
            Err(AuthorityError::ObservationExpired)
        );
        let (mut b, _, _) = viewing_with_control(at(0));
        b.issue_observation_challenge(0xdef, at(2_000_000)).unwrap();
        assert_eq!(
            b.respond_observation_challenge(0x111, at(2_100_000)),
            Err(AuthorityError::ChallengeMismatch)
        );
        assert_eq!(
            b.respond_observation_challenge(0xdef, at(2_200_000)),
            Ok(at(5_000_000))
        );
    }

    #[test]
    fn controller_slot_is_busy_until_revoked_then_handoff_serializes() {
        let (mut a, first, _) = viewing_with_control(at(0));
        let second = InputLeaseId::from_raw(42);
        assert_eq!(a.grant_lease(second, at(100_000)), Err(AuthorityError::ControllerBusy));
        a.revoke_lease();
        a.grant_lease(second, at(200_000)).unwrap();
        let ticket = InputTicketId::from_raw(7);
        a.issue_input_ticket(second, ticket, at(200_000)).unwrap();
        assert_eq!(a.authorize_submission(first, ticket, at(200_100)), Err(AuthorityError::StaleLease));
    }

    #[test]
    fn resume_boundary_retires_a_lapsed_lease_across_a_clock_jump() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        let resumed = at(10_000_000);
        assert!(!a.apply_resume_boundary(resumed));
        assert!(!a.has_live_control(resumed));
        assert_eq!(a.readiness(), ViewReadiness::Unready);
        assert_eq!(a.phase(), Phase::CapabilitiesChecked);
        assert_eq!(
            a.authorize_submission(lease, ticket, resumed),
            Err(AuthorityError::InvalidState { phase: Phase::CapabilitiesChecked })
        );
        a.authorize_observation(resumed).unwrap();
        a.mark_view_ready(resumed).unwrap();
        assert_eq!(a.authorize_submission(lease, ticket, resumed), Err(AuthorityError::NoLease));
    }

    #[test]
    fn resume_boundary_keeps_a_live_lease_but_can_expire_only_its_ticket() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        a.issue_control_challenge(5, at(100_000)).unwrap();
        assert_eq!(a.respond_control_challenge(lease, 5, at(150_000)), Ok(at(3_100_000)));
        let resumed = at(1_200_000);
        assert!(a.apply_resume_boundary(resumed));
        assert_eq!(a.authorize_submission(lease, ticket, resumed), Err(AuthorityError::TicketInvalid));
        let next = InputTicketId::from_raw(77);
        a.issue_input_ticket(lease, next, resumed).unwrap();
        assert_eq!(a.authorize_submission(lease, next, resumed), Ok(()));
    }

    #[test]
    fn ticket_lifetime_is_clamped_to_the_lease_authorization() {
        let (mut a, lease, _) = viewing_with_control(at(0));
        let ticket = InputTicketId::from_raw(9);
        assert_eq!(a.issue_input_ticket(lease, ticket, at(2_800_000)), Ok(at(3_000_000)));
    }

    #[test]
    fn close_and_revoke_are_terminal() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        a.close();
        assert_eq!(a.phase(), Phase::Closed);
        assert_eq!(
            a.authorize_submission(lease, ticket, at(1)),
            Err(AuthorityError::InvalidState { phase: Phase::Closed })
        );
    }

    #[test]
    fn control_cannot_outlive_observation() {
        let (mut a, lease, _) = viewing_with_control(at(0));
        a.issue_control_challenge(1, at(1_000_000)).unwrap();
        a.respond_control_challenge(lease, 1, at(1_500_000)).unwrap();
        let ticket = InputTicketId::from_raw(5);
        assert_eq!(a.issue_input_ticket(lease, ticket, at(2_800_000)), Ok(at(3_000_000)));
        a.issue_control_challenge(2, at(2_900_000)).unwrap();
        assert_eq!(a.authorize_submission(lease, ticket, at(3_500_000)), Err(AuthorityError::ObservationExpired));
        assert_eq!(a.issue_input_ticket(lease, InputTicketId::from_raw(6), at(3_500_000)), Err(AuthorityError::ObservationExpired));
        assert_eq!(a.respond_control_challenge(lease, 2, at(3_500_000)), Err(AuthorityError::ObservationExpired));
        assert!(!a.has_live_control(at(3_500_000)));
    }

    #[test]
    fn expired_observation_blocks_view_ready_and_grant() {
        let (session, lease, _) = ids();
        let mut a = SessionAuthority::new(session, AuthorityPolicy::plan_defaults());
        a.mark_capabilities_checked().unwrap();
        a.authorize_observation(at(0)).unwrap();
        assert_eq!(a.mark_view_ready(at(3_000_000)), Err(AuthorityError::ObservationExpired));
        assert_eq!(a.grant_lease(lease, at(3_000_000)), Err(AuthorityError::ObservationExpired));
    }

    #[test]
    fn refusal_clears_every_authority_path() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        a.issue_observation_challenge(11, at(1)).unwrap();
        a.issue_control_challenge(12, at(1)).unwrap();
        a.refuse();
        let refused = Err(AuthorityError::InvalidState { phase: Phase::Refused });
        assert!(!a.has_live_control(at(2)));
        assert_eq!(a.authorize_observation_delivery(at(2)), refused);
        assert_eq!(a.authorize_submission(lease, ticket, at(2)), refused);
        assert_eq!(a.respond_observation_challenge(11, at(2)), refused.map(|()| at(0)));
        assert_eq!(a.respond_control_challenge(lease, 12, at(2)), refused.map(|()| at(0)));
        assert_eq!(a.issue_input_ticket(lease, ticket, at(2)), refused.map(|()| at(0)));
        assert_eq!(a.issue_observation_challenge(13, at(2)), refused.map(|()| at(0)));
        assert_eq!(a.readiness(), ViewReadiness::Unready);
    }

    #[test]
    fn old_observation_challenge_does_not_survive_a_new_grant() {
        let (mut a, _, _) = viewing_with_control(at(0));
        a.issue_observation_challenge(7, at(2_000_000)).unwrap();
        assert!(!a.apply_resume_boundary(at(3_000_000)));
        a.require_approval().unwrap();
        a.authorize_observation(at(3_000_000)).unwrap();
        assert_eq!(a.respond_observation_challenge(7, at(3_000_001)), Err(AuthorityError::ChallengeMismatch));
    }

    #[test]
    fn delayed_replies_do_not_shift_challenge_deadlines() {
        let (mut a, lease, _) = viewing_with_control(at(0));
        let observation = a.issue_observation_challenge(1, at(1_000_000)).unwrap();
        let control = a.issue_control_challenge(2, at(1_000_000)).unwrap();
        assert_eq!(a.respond_observation_challenge(1, at(2_900_000)), Ok(observation));
        assert_eq!(a.respond_control_challenge(lease, 2, at(2_900_000)), Ok(control));
        assert_eq!(observation, at(4_000_000));
        assert_eq!(control, at(4_000_000));
        assert!(!a.has_live_control(at(4_000_000)));
    }

    #[test]
    fn clock_regression_fences_instead_of_resurrecting_expired_input() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        assert_eq!(a.authorize_submission(lease, ticket, at(1_000_000)), Err(AuthorityError::TicketExpired));
        assert_eq!(a.authorize_submission(lease, ticket, at(999_999)), Err(AuthorityError::ClockRegression));
        assert_eq!(a.phase(), Phase::Closed);
        assert_eq!(a.authorize_submission(lease, ticket, at(1_000_001)), Err(AuthorityError::ClockRegression));
        assert!(!a.has_live_control(at(1_000_001)));
    }

    #[test]
    fn suspend_fences_even_a_paused_clock_and_clears_challenges() {
        let (mut a, lease, ticket) = viewing_with_control(at(0));
        a.issue_observation_challenge(1, at(0)).unwrap();
        a.invalidate_for_suspend();
        assert!(!a.has_live_control(at(0)));
        a.require_approval().unwrap();
        a.authorize_observation(at(0)).unwrap();
        a.mark_view_ready(at(0)).unwrap();
        assert_eq!(a.authorize_submission(lease, ticket, at(0)), Err(AuthorityError::NoLease));
        assert_eq!(a.respond_observation_challenge(1, at(0)), Err(AuthorityError::ChallengeMismatch));
    }

    #[test]
    fn pending_challenge_is_not_overwritten_by_the_next_cadence_tick() {
        let (mut a, lease, _) = viewing_with_control(at(0));
        a.issue_observation_challenge(1, at(100_000)).unwrap();
        a.issue_control_challenge(2, at(100_000)).unwrap();
        assert_eq!(a.issue_observation_challenge(3, at(1_100_000)), Err(AuthorityError::ChallengePending));
        assert_eq!(a.issue_control_challenge(4, at(1_100_000)), Err(AuthorityError::ChallengePending));
        assert_eq!(a.respond_observation_challenge(1, at(1_500_000)), Ok(at(3_100_000)));
        assert_eq!(a.respond_control_challenge(lease, 2, at(1_500_000)), Ok(at(3_100_000)));
        assert_eq!(a.respond_observation_challenge(1, at(1_500_001)), Err(AuthorityError::ChallengeMismatch));
    }

    #[test]
    fn expired_controller_needs_explicit_cleanup_before_replacement() {
        let (mut a, _, _) = viewing_with_control(at(0));
        a.issue_observation_challenge(1, at(2_000_000)).unwrap();
        a.respond_observation_challenge(1, at(2_100_000)).unwrap();
        let replacement = InputLeaseId::from_raw(9);
        assert_eq!(a.grant_lease(replacement, at(3_000_000)), Err(AuthorityError::ControllerCleanupRequired));
        a.revoke_lease();
        assert_eq!(a.grant_lease(replacement, at(3_000_000)), Ok(()));
    }

    #[test]
    fn deadline_overflow_cannot_mint_a_saturated_challenge() {
        let (mut a, _, _) = viewing_with_control(at(u64::MAX - 3_000_000));
        assert_eq!(a.issue_observation_challenge(1, at(u64::MAX - 2_000_000)), Err(AuthorityError::DeadlineOverflow));
        assert!(a.observation_challenge.is_none());
    }
}
