use fr_core::limits::ProtocolLimits;
use fr_wire::*;

fn limits() -> MediaLimits { MediaLimits::new(ProtocolLimits::ABSOLUTE, 1_150, 16_384, 64).unwrap() }
fn descriptor(reference: Option<u64>) -> FrameDescriptor {
    FrameDescriptor { frame: 7, total_bytes: 3, stride: 8, capture_micros: 42, reference }
}
fn hex(s: &str) -> Vec<u8> {
    s.as_bytes().chunks_exact(2).map(|pair| {
        u8::from_str_radix(core::str::from_utf8(pair).unwrap(), 16).unwrap()
    }).collect()
}
fn fragment_bytes() -> Vec<u8> {
    // Independently specified big-endian fixture, not generated by the encoder.
    hex("4652443000000034000000000000002c000000090000000000000000000000070000000300000000000000000000000100000008000000000000002a0000000003010203")
}
#[test]
fn golden_fragment_is_byte_exact_and_borrowed() {
    let expected = fragment_bytes();
    let mut out = [0_u8; 128];
    let n = encode_fragment(Fragment { descriptor: descriptor(None), index: 0, bytes: &[1, 2, 3] }, 9, &limits(), &mut out).unwrap();
    assert_eq!(&out[..n], expected);
    let record = Record::decode(&expected, &limits(), 9, Channel::Video).unwrap();
    let fragment = decode_fragment(record, &limits()).unwrap();
    assert_eq!(fragment.descriptor, descriptor(None));
    assert_eq!(fragment.bytes, &[1, 2, 3]);
    assert_eq!(fragment.bytes.as_ptr(), expected[65..].as_ptr());
}
#[test]
fn every_truncation_is_refused() {
    let bytes = fragment_bytes();
    for length in 0..bytes.len() {
        assert!(Record::decode(&bytes[..length], &limits(), 9, Channel::Video).is_err());
    }
    let mut trailing = bytes.clone(); trailing.push(0);
    assert_eq!(Record::decode(&trailing, &limits(), 9, Channel::Video).unwrap_err(), WireError::TrailingBytes);
}
#[test]
fn framing_refuses_bad_magic_version_flags_binding_and_channel() {
    for (offset, value, error) in [
        (0, 0, WireError::BadMagic), (5, 1, WireError::UnsupportedVersion),
        (7, 0xff, WireError::UnsupportedKind), (9, 1, WireError::InvalidFlags),
        (11, 1, WireError::InvalidFlags), (19, 10, WireError::InvalidBinding),
    ] {
        let mut bytes = fragment_bytes(); bytes[offset] = value;
        assert_eq!(Record::decode(&bytes, &limits(), 9, Channel::Video).unwrap_err(), error);
    }
    assert_eq!(Record::decode(&fragment_bytes(), &limits(), 9, Channel::Control).unwrap_err(), WireError::WrongChannel);
    assert_eq!(Record::decode(&fragment_bytes(), &limits(), 0, Channel::Video).unwrap_err(), WireError::InvalidBinding);
}
#[test]
fn fragment_geometry_and_dependencies_are_checked() {
    let l = limits();
    for offset in [35, 39, 43, 47] {
        let mut bytes = fragment_bytes(); bytes[offset] = 2;
        let record = Record::decode(&bytes, &l, 9, Channel::Video).unwrap();
        assert!(decode_fragment(record, &l).is_err(), "offset {offset}");
    }
    assert_eq!(descriptor(Some(7)).validate(&l), Err(WireError::InvalidDependency));
    assert_eq!(descriptor(Some(8)).validate(&l), Err(WireError::InvalidDependency));
    let mut d = descriptor(None); d.stride = 0;
    assert!(d.validate(&l).is_err());
    d.stride = 1; d.total_bytes = 16_385;
    assert_eq!(d.validate(&l), Err(WireError::ResourceLimit));
    d.total_bytes = u32::MAX;
    assert_eq!(d.validate(&l), Err(WireError::ResourceLimit));
}
#[test]
fn predicted_fragments_round_trip_including_short_tail() {
    let l = limits();
    let bytes: Vec<u8> = (0..100).collect();
    let d = FrameDescriptor { total_bytes: 100, stride: 31, reference: Some(6), ..descriptor(None) };
    for index in 0..d.fragment_count().unwrap() {
        let fragment = Fragment { descriptor: d, index, bytes: &bytes[d.fragment_range(index).unwrap()] };
        let mut out = [0_u8; 1_150];
        let n = encode_fragment(fragment, 9, &l, &mut out).unwrap();
        let parsed = decode_fragment(Record::decode(&out[..n], &l, 9, Channel::Video).unwrap(), &l).unwrap();
        assert_eq!(parsed.descriptor, d); assert_eq!(parsed.index, index); assert_eq!(parsed.bytes, fragment.bytes);
    }
}
#[test]
fn recovery_chunks_and_progress_round_trip() {
    let l = limits(); let mut out = [0_u8; 1_150];
    let n = encode_recovery(RecoveryChunk { frame: 7, total_bytes: 10, offset: 6, capture_micros: 42, bytes: &[1, 2, 3, 4] }, 9, &l, &mut out).unwrap();
    let chunk = decode_recovery(Record::decode(&out[..n], &l, 9, Channel::Recovery).unwrap(), &l).unwrap();
    assert_eq!(chunk.offset, 6); assert_eq!(chunk.bytes, &[1, 2, 3, 4]);
    for observation in [SourceObservation::Unknown, SourceObservation::Captured, SourceObservation::QualifiedUnchanged] {
        let progress = Progress { descriptor: descriptor(Some(6)), observed_micros: 45, observation, pipeline: PipelineState::Idle };
        let n = encode_progress(progress, 9, &l, &mut out).unwrap();
        assert_eq!(decode_progress(Record::decode(&out[..n], &l, 9, Channel::MediaConfig).unwrap(), &l), Ok(progress));
    }
}
#[test]
fn repair_ranges_are_bounded_sorted_and_nonoverlapping() {
    let l = limits(); let mut out = [0_u8; 1_150];
    let ranges = [RepairRange { start: 0, end: 2 }, RepairRange { start: 4, end: 5 }];
    let n = encode_repair(7, &ranges, 5, 9, &l, &mut out).unwrap();
    let request = decode_repair(Record::decode(&out[..n], &l, 9, Channel::Control).unwrap(), 5, &l).unwrap();
    assert_eq!(request.frame, 7); assert_eq!(request.ranges().collect::<Vec<_>>(), ranges);
    for ranges in [vec![], vec![RepairRange { start: 0, end: 0 }], vec![RepairRange { start: 0, end: 6 }], vec![RepairRange { start: 1, end: 3 }, RepairRange { start: 2, end: 4 }]] {
        assert!(encode_repair(7, &ranges, 5, 9, &l, &mut out).is_err());
    }
    let mut forged = out;
    forged[32..36].copy_from_slice(&u32::MAX.to_be_bytes());
    let record = Record::decode(&forged[..n], &l, 9, Channel::Control).unwrap();
    assert_eq!(decode_repair(record, 5, &l).unwrap_err(), WireError::InvalidRanges);
}
#[test]
fn optional_extensions_skip_but_required_and_duplicate_tags_refuse() {
    let mut bytes = fragment_bytes();
    bytes.extend_from_slice(&[0, 1, 0, 0, 0, 0, 0, 1, 99]);
    bytes[12..16].copy_from_slice(&53_u32.to_be_bytes());
    bytes[20..24].copy_from_slice(&9_u32.to_be_bytes());
    let l = limits();
    let record = Record::decode(&bytes, &l, 9, Channel::Video).unwrap();
    assert_eq!(decode_fragment(record, &l).unwrap().bytes, &[1, 2, 3]);
    bytes[71] = 1;
    assert_eq!(Record::decode(&bytes, &l, 9, Channel::Video).unwrap_err(), WireError::RequiredExtension);
    bytes[71] = 0;
    bytes.extend_from_slice(&[0, 1, 0, 0, 0, 0, 0, 0]);
    bytes[12..16].copy_from_slice(&61_u32.to_be_bytes());
    bytes[20..24].copy_from_slice(&17_u32.to_be_bytes());
    assert_eq!(Record::decode(&bytes, &l, 9, Channel::Video).unwrap_err(), WireError::InvalidExtension);
}
#[test]
fn payloads_never_appear_in_debug_output() {
    let first = fragment_bytes(); let mut second = first.clone();
    second[65..].copy_from_slice(&[99, 88, 77]);
    let l = limits();
    let a = Record::decode(&first, &l, 9, Channel::Video).unwrap();
    let b = Record::decode(&second, &l, 9, Channel::Video).unwrap();
    assert_eq!(format!("{a:?}"), format!("{b:?}"));
    assert_eq!(format!("{:#?}", decode_fragment(a, &l).unwrap()), format!("{:#?}", decode_fragment(b, &l).unwrap()));
}
#[test]
fn encoder_respects_actual_packet_and_destination_limits() {
    let p = ProtocolLimits::ABSOLUTE;
    assert!(MediaLimits::new(p, 73, 16_384, 64).is_err());
    assert!(MediaLimits::new(p, 65_537, 16_384, 64).is_err());
    assert!(MediaLimits::new(p, 1_150, 0, 64).is_err());
    let l = limits();
    let f = Fragment { descriptor: descriptor(None), index: 0, bytes: &[1, 2, 3] };
    assert_eq!(encode_fragment(f, 9, &l, &mut [0; 4]), Err(WireError::BufferTooSmall));
    let d = FrameDescriptor { total_bytes: 1_077, stride: 1_077, reference: Some(6), ..descriptor(None) };
    let data = vec![1; 1_077]; let mut out = [0; 1_150];
    assert_eq!(encode_fragment(Fragment { descriptor: d, index: 0, bytes: &data }, 9, &l, &mut out), Ok(1_150));
}
