#!/usr/bin/env python3
"""Fixed repository line-counting command for FrankenRemote.

Enforces size discipline per AGENTS.md Section 3.7 and Plan Section 22.2:
- 194,000 target handwritten Rust lines
- 240,000 planned maximum
- 250,000 hard stop (refusal)
- 20,000 separate allowance for non-Rust glue (JS/Swift/Kotlin/C/Python/shell)

Reports handwritten Rust, generated bindings, non-Rust glue, vendored source,
and project-induced upstream changes as separate numbers.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

# Budget thresholds
RUST_TARGET_LINES = 194_000
RUST_PLANNED_MAX_LINES = 240_000
RUST_HARD_STOP_LINES = 250_000
GLUE_ALLOWANCE_LINES = 20_000

# File classifications
RUST_EXTS = {".rs"}
GLUE_EXTS = {
    ".js", ".mjs", ".ts",
    ".swift", ".kt", ".java",
    ".c", ".h", ".cpp",
    ".py", ".sh", ".ps1"
}

IGNORE_DIRS = {
    ".git", ".beads", "target", "out", "node_modules",
    "build", "dist", ".claude", ".gemini", "__pycache__",
    ".system_generated", "fixtures"
}

GENERATED_MARKERS = [
    b"@generated",
    b"generated by",
    b"bindgen",
    b"automatically generated",
]


def count_file_lines(path: Path) -> tuple[int, bool]:
    """Count lines in file and check if it is generated code."""
    try:
        with open(path, "rb") as fp:
            content = fp.read()
    except (OSError, PermissionError):
        return 0, False

    lines = content.count(b"\n")
    if content and not content.endswith(b"\n"):
        lines += 1

    first_kib = content[:2048].lower()
    is_generated = any(marker in first_kib for marker in GENERATED_MARKERS)
    if "generated" in path.name.lower():
        is_generated = True

    return lines, is_generated


def scan_directory(root_dir: Path) -> dict:
    """Scan and categorize lines of code across the directory."""
    rust_handwritten_by_crate: dict[str, int] = {}
    rust_handwritten_total = 0
    generated_bindings_total = 0
    glue_by_ext: dict[str, int] = {}
    glue_total = 0
    vendored_total = 0
    upstream_total = 0

    crates_dir = root_dir / "crates"

    for root, dirs, files in os.walk(root_dir):
        # Prune ignored directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS and not d.startswith(".")]

        rel_root = Path(root).relative_to(root_dir)
        path_parts = rel_root.parts

        is_vendor = "vendor" in path_parts
        is_upstream = "upstream" in path_parts or "patches" in path_parts

        for f in files:
            file_path = Path(root) / f
            ext = file_path.suffix.lower()

            if is_vendor:
                lines, _ = count_file_lines(file_path)
                vendored_total += lines
                continue

            if is_upstream:
                lines, _ = count_file_lines(file_path)
                upstream_total += lines
                continue

            if ext in RUST_EXTS:
                lines, is_gen = count_file_lines(file_path)
                if is_gen:
                    generated_bindings_total += lines
                else:
                    rust_handwritten_total += lines
                    # Determine crate name if in crates/
                    if crates_dir.exists() and file_path.is_relative_to(crates_dir):
                        crate_name = file_path.relative_to(crates_dir).parts[0]
                    else:
                        crate_name = path_parts[0] if path_parts else "root"
                    rust_handwritten_by_crate[crate_name] = (
                        rust_handwritten_by_crate.get(crate_name, 0) + lines
                    )
            elif ext in GLUE_EXTS:
                lines, is_gen = count_file_lines(file_path)
                if is_gen:
                    generated_bindings_total += lines
                else:
                    glue_total += lines
                    glue_by_ext[ext] = glue_by_ext.get(ext, 0) + lines

    return {
        "rust_handwritten": {
            "total": rust_handwritten_total,
            "by_crate": rust_handwritten_by_crate,
            "target": RUST_TARGET_LINES,
            "planned_max": RUST_PLANNED_MAX_LINES,
            "hard_stop": RUST_HARD_STOP_LINES,
        },
        "generated_bindings": {
            "total": generated_bindings_total,
        },
        "non_rust_glue": {
            "total": glue_total,
            "by_extension": glue_by_ext,
            "allowance": GLUE_ALLOWANCE_LINES,
        },
        "vendored_source": {
            "total": vendored_total,
        },
        "upstream_changes": {
            "total": upstream_total,
        },
    }


def format_report(stats: dict) -> str:
    """Format human-readable line count report."""
    rust_stats = stats["rust_handwritten"]
    glue_stats = stats["non_rust_glue"]
    gen_stats = stats["generated_bindings"]
    vendor_stats = stats["vendored_source"]
    upstream_stats = stats["upstream_changes"]

    rust_total = rust_stats["total"]
    glue_total = glue_stats["total"]

    lines = [
        "================================================================================",
        "                     FRANKENREMOTE SIZE DISCIPLINE AUDIT",
        "================================================================================",
        "",
        "1. HANDWRITTEN RUST BREAKDOWN (by crate / directory):",
        "--------------------------------------------------------------------------------",
    ]

    for crate, count in sorted(rust_stats["by_crate"].items(), key=lambda x: -x[1]):
        pct = (count / rust_total * 100) if rust_total > 0 else 0
        lines.append(f"  {crate:<24}: {count:>8,} lines ({pct:>5.1f}%)")

    lines.extend([
        "--------------------------------------------------------------------------------",
        f"  Total Handwritten Rust    : {rust_total:>8,} lines",
        f"  Target Budget             : {RUST_TARGET_LINES:>8,} lines",
        f"  Planned Maximum           : {RUST_PLANNED_MAX_LINES:>8,} lines",
        f"  Hard Stop Ceiling         : {RUST_HARD_STOP_LINES:>8,} lines",
        "",
        "2. NON-RUST GLUE BREAKDOWN (JS / Swift / Kotlin / C / Python / Shell):",
        "--------------------------------------------------------------------------------",
    ])

    for ext, count in sorted(glue_stats["by_extension"].items(), key=lambda x: -x[1]):
        lines.append(f"  {ext:<24}: {count:>8,} lines")

    lines.extend([
        "--------------------------------------------------------------------------------",
        f"  Total Non-Rust Glue       : {glue_total:>8,} lines",
        f"  Allowance Ceiling         : {GLUE_ALLOWANCE_LINES:>8,} lines",
        "",
        "3. OTHER CATEGORIES (Reported Separately per AGENTS.md 3.7):",
        "--------------------------------------------------------------------------------",
        f"  Generated Bindings        : {gen_stats['total']:>8,} lines",
        f"  Vendored Source           : {vendor_stats['total']:>8,} lines",
        f"  Project Upstream Changes  : {upstream_stats['total']:>8,} lines",
        "================================================================================",
    ])

    # Status verdicts
    rust_ok = rust_total <= RUST_HARD_STOP_LINES
    glue_ok = glue_total <= GLUE_ALLOWANCE_LINES

    if not rust_ok:
        lines.append(
            f"VERDICT: REFUSAL - Handwritten Rust ({rust_total:,}) exceeds "
            f"hard stop ({RUST_HARD_STOP_LINES:,})!"
        )
    elif rust_total > RUST_PLANNED_MAX_LINES:
        lines.append(
            f"VERDICT: WARNING - Handwritten Rust ({rust_total:,}) exceeds "
            f"planned maximum ({RUST_PLANNED_MAX_LINES:,}) but remains within hard stop."
        )
    elif rust_total > RUST_TARGET_LINES:
        lines.append(
            f"VERDICT: PASS (CONTINGENCY) - Handwritten Rust ({rust_total:,}) exceeds "
            f"194k target but remains within planned max ({RUST_PLANNED_MAX_LINES:,})."
        )
    else:
        lines.append(
            f"VERDICT: PASS - Handwritten Rust ({rust_total:,}) is within the 194k target."
        )

    if not glue_ok:
        lines.append(
            f"VERDICT: REFUSAL - Non-Rust glue ({glue_total:,}) exceeds "
            f"20k allowance ({GLUE_ALLOWANCE_LINES:,})!"
        )
    else:
        lines.append(
            f"VERDICT: PASS - Non-Rust glue ({glue_total:,}) is within the 20k allowance."
        )

    lines.append("================================================================================")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Fixed line-counting tool for FrankenRemote")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                        help="Root directory to scan (default: repository root)")
    parser.add_argument("--fixture", type=Path, default=None,
                        help="Scan a fixture directory instead of repo root")
    parser.add_argument("--json", action="store_true",
                        help="Output JSON summary")
    parser.add_argument("--check", action="store_true", default=True,
                        help="Enforce budgets and exit nonzero on violation")

    args = parser.parse_args()

    scan_root = args.fixture if args.fixture else args.root
    if not scan_root.exists():
        sys.stderr.write(f"Error: path does not exist: {scan_root}\n")
        return 2

    stats = scan_directory(scan_root)

    rust_total = stats["rust_handwritten"]["total"]
    glue_total = stats["non_rust_glue"]["total"]

    if args.json:
        stats["verdict"] = {
            "rust_passed": rust_total <= RUST_HARD_STOP_LINES,
            "glue_passed": glue_total <= GLUE_ALLOWANCE_LINES,
            "overall_passed": (rust_total <= RUST_HARD_STOP_LINES) and (glue_total <= GLUE_ALLOWANCE_LINES),
        }
        print(json.dumps(stats, indent=2))
    else:
        print(format_report(stats))

    if args.check:
        if rust_total > RUST_HARD_STOP_LINES:
            sys.stderr.write(
                f"\nOVER_BUDGET_REFUSAL: Handwritten Rust lines ({rust_total:,}) "
                f"exceed hard stop of {RUST_HARD_STOP_LINES:,} lines.\n"
            )
            return 1
        if glue_total > GLUE_ALLOWANCE_LINES:
            sys.stderr.write(
                f"\nOVER_BUDGET_REFUSAL: Non-Rust glue lines ({glue_total:,}) "
                f"exceed allowance of {GLUE_ALLOWANCE_LINES:,} lines.\n"
            )
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
